### ISSUE TITLE
sql import error on xampp server.

### ISSUE THREAD

**Issue by imoldovavan** [jxmx/smooth-qsl#12]
--
-- Table structure for table `trans`
--

--DROP TABLE IF EXISTS `trans`;
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '--DROP TABLE IF EXISTS `trans`' at line 5

**Comment by jxmx** [comment]
@imoldovavan - What version of MariaDB are you using?

**Comment by imoldovavan** [comment]
MariaDB 10.4.28
XAMPP Version: 8.2.4

**Comment by jxmx** [comment]
@imoldovavan I can't immediately reproduce an SQL error that your showing above. Is this when you're loading the database for the first time? MariaDB 10.4 is obsolete; can you use a newer version? I don't use XAMPP so I don't know what your options are.

**Comment by michelinok** [comment]
You must remove the  "--" , you can find this "error" also on all the other Drop Table inside the sql file.

**Comment by jxmx** [comment]
The `--` is there on purpose because in most cases you don't want to drop the existing tables because they presumably have data in them. However the original error as reported is that @imoldovavan server is saying that `--` is an invalid command itself which it isn't.

**Comment by jxmx** [comment]
Can't reproduce
