### ISSUE TITLE
Error in qsladifloadcommit.php

### ISSUE THREAD

**Issue by michelinok** [jxmx/smooth-qsl#13]
Hi!
I'm still not able to do a pull request...
The last line of qsladifloadcommit.php is not good,it must read

<?php include("../qslmaint.php"); ?>

It's missing the "../" and the php terminator

'73 de iu5hes Michele

**Comment by jxmx** [comment]
Oops. Thanks!

**Comment by jxmx** [comment]
Fixed in #14
